name: Github T00ls Auto Sign
 
on:
    push:
        branches:
            - main
    schedule:
        - cron: '30 16 * * *'
jobs:
    build:
        runs-on: ubuntu-latest
 
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
#                 python-version: '3.8'
                python-version: '2.7'
                architecture: x64
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Run
              env:
                USERNAME: ${{ secrets.USERNAME }}
                PASSWORD: ${{ secrets.PASSWORD }}
                QUESTION: ${{ secrets.QUESTION }}
                ANSWER: ${{ secrets.ANSWER }}
                USERNAME1: ${{ secrets.USERNAME1 }}
                PASSWORD1: ${{ secrets.PASSWORD1 }}
                QUESTION1: ${{ secrets.QUESTION1 }}
                ANSWER1: ${{ secrets.ANSWER1 }}
                SCKEY:  ${{secrets.SCKEY}}
#               run: python t00ls.py & python t00ls2.py
              run: python 1.py 

              
          
              
